# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogininvalido():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logininvalido(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(1353, 706)
    assert self.driver.find_element(By.ID, "perfil-hidden").text == "PERFIL"
    self.driver.find_element(By.ID, "perfil-hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("702.188.648-92")
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("sucesso2024")
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".font_erro").text == "e-mail ou senha inválidos!"
  
