# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAcessoComSucesso():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_acessoComSucesso(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(1382, 722)
    assert self.driver.find_element(By.ID, "perfil-hidden").text == "PERFIL"
    self.driver.find_element(By.ID, "perfil-hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("776.631.466-54")
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("!Saopaulo123")
    assert self.driver.find_element(By.ID, "ContentSite_ibtContinue").text == "Continuar"
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#lblWelcome > b").text == "Marlene"
  
