
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastrousuario():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrousuario(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(1353, 706)
    assert self.driver.find_element(By.ID, "perfil-hidden").text == "PERFIL"
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    assert self.driver.find_element(By.ID, "ContentSite_ibtNewCustomer").text == "Criar cadastro"
    self.driver.find_element(By.ID, "ContentSite_ibtNewCustomer").click()
    self.driver.find_element(By.ID, "ContentSite_txtName").click()
    self.driver.find_element(By.ID, "ContentSite_txtName").send_keys("Esther Clarice Martins")
    self.driver.find_element(By.ID, "ContentSite_txtCpf").click()
    self.driver.find_element(By.ID, "ContentSite_txtCpf").send_keys("702.188.648-92")
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("estherclaricemartins@destribuidorapetfarma.com.br")
    self.driver.find_element(By.ID, "ContentSite_txtPasswordNew").click()
    self.driver.find_element(By.ID, "ContentSite_txtPasswordNew").click()
    self.driver.find_element(By.ID, "ContentSite_txtPasswordNew").send_keys("0MOyuCcp31")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtZip").click()
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtZip").send_keys("13940-971")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "ContentSite_btnCreateCustomer").click()
    element = self.driver.find_element(By.ID, "ContentSite_btnCreateCustomer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,73)")
  
